### PR TITLE
Associate is lower in rank than a Specialist

### PR DESCRIPTION
**Pull request by marbeann**
An associate is a person who is part of a work team or a collaborative partner towards a specific goal. However, a specialist is a person who is an expert at something and will in many instances work independently.

Source: https://careertrend.com/info-8610586-associate-versus-specialist.html

### CODE REVIEW

**Comment by marbeann** [comment]
Will then also need to update our handbook the same way. https://github.com/niteoweb/handbook/blob/master/5_People/career-operations.md

**Comment by dmurko** [comment]
This comes from Glassdoor.

**Comment by marbeann** [comment]
Doesn't makes sense at all but sure.

**Comment by dmurko** [comment]
I know, it's just that we can't change it as long as we're sourcing base salaries from there.

**Pull request closed without merging**
