### PR TITLE
Publish compiled Elm code to use directly on niteo.co

### PR DESCRIPTION
**Pull request by zupo**
* [ ] fix .gitignore
* [ ] in CI, ensure that the developer remembered to run `make dist && git add dist/index.js`

### CODE REVIEW

**Comment by zupo** [comment]
https://raw.githubusercontent.com/ does not set proper content_type. jsdeliver.net acts as a workaround. So I can use the compiled JS directly in any HTML file: https://cdn.jsdelivr.net/gh/niteoweb/salarycalc@add/publish_index.js/dist/index.js

I've tested with minisites running locally and it seems to work fine:

Screenshot 2019-03-21 at 14 34 18

**Comment by zupo** [comment]
One consideration: what if we change this path and forget to update minisites? Then salary calc on minisites is broken and we don't notice it. 

-> Only until a build is ran on minisites. We have a browser test on minisites that verifies salary calc is working. This test will fail if salarycalc code does not load correctly.

**Comment by zupo** [comment]
Also works as a Review App:

Screenshot 2019-03-21 at 14 45 40

**Comment by lzrski** [comment]
I really don't like checking in compiled code into Git. It's just asking for bugs that are difficult to figure out. And I don't feel we will save anything it terms of complexity once we get to implement the items from your checklist.

Of course it's your project, so we will do as you prefer.

**Comment by zupo** [comment]
> It's just asking for bugs that are difficult to figure out.

Can you elaborate? Possibly provide examples? My experience is exactly the opposite. If we don't have compiled JS in git, it never really compiles deterministically in different systems and we get obscure bugs. But I'm very much an anti-JS person and it's showing. I'm really eager to learn what kind of bugs can come from committing compiled JS!

**Comment by lzrski** [comment]
One that you mentioned yourself: developer forgets to push compiled code and expects that changes she made to the source are deployed in production. In fact production runs the old version. Or code is compiled in development mode (without optimizations) and then pushed.

I agree that compiling JS upon installation is not very reliable. Ultimately I think we should compile and deploy it somewhere using CI. With #4 it's just a step away. We can use NPM (the most popular distribution channel for front-end libraries) or a CDN. Preferably both.

**Comment by zupo** [comment]
> developer forgets to push compiled code and expects that changes she made to the source are deployed in production. In fact production runs the old version.

We check for this in CI and CI fails if that is the case. Code-without-compile cannot get pushed to production. 

I understand this is a coping mechanism that we, as backend people, have developed to guard as against JS shenanigans. Not ideal :)

**Comment by lzrski** [comment]
I see your point. Development for browser is surely (over?) complicated and brittle. That's one of the driving factors for Elm.

That said I would still go with #4. You are willing to write CI logic to check if code was correctly compiled. Why not just compile it in CI? Publishing should not be a problem. If you want we can have a call tomorrow and I can walk you through integration with minisites.

Alternatively you can just make a call to continue with this branch.

**Comment by zupo** [comment]
Had a good Zoom talk, here are the conclusions:

```
The PlanTM:

* publish new version to NPM with CircleCI on every master push
    -> version number is 1.0.0-YEAR-MONTH-DAY-HOUR-MINUTE-SECOND
* for now in minisites use a <script> tag and load the Elm code directly
  form NPN via https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
  -> in the future, we might pin this down to load a specific version
     via https://cdn.jsdelivr.net/npm/jquery@3.2/dist/jquery.min.js


-> we removed the manual required `make dist` step (yay!) in salarycalc (because CI publishes the compiled code)
-> nothing needs to change in minisites to get a new version of salarycalc
-> all of the above assumes master in salarycalc is very stable (as we are used with all other Niteo repositories)
```

**Comment by zupo** [comment]
Not needed.

**Pull request closed without merging**
