### PR TITLE
Automate calculating locationFactors and baseSalaries

### PR DESCRIPTION
**Pull request by zupo**

### CODE REVIEW

**Comment by zupo** [comment]
@marbeann, @dmurko: check the changes since last year: mostly salaries will go down a tiny bit.

**Comment by zupo** [comment]
Glassdoor as a source of salary bases is useless. `Junior Software Engineer` average salary increased 30% since January while `Software Engineer` stayed almost exactly the same, and today, the salaries for both are basically the same.

Screenshot 2019-12-06 at 15 02 25

Screenshot 2019-12-06 at 15 02 32

**Comment by marbeann** [comment]
Wow. Designer is higher than Senior Designer and Lead Designer.

Screen Shot 2019-12-07 at 01 09 49

It just seems off that the base salary for a junior position is the same as the senior role.

Screen Shot 2019-12-07 at 01 10 08

Screen Shot 2019-12-07 at 01 12 42

**Comment by dmurko** [comment]
Yeah, this won't work. Hopefully I get at least one good offer for the data in the coming two weeks.

**Comment by zupo** [comment]
Numbeo is pretty decent though.

**Comment by zupo** [comment]
Superseded by https://github.com/niteoweb/salarycalc/pull/44.

**Pull request closed without merging**
